### ISSUE TITLE
Искуственный интеллект для врагов

### ISSUE THREAD

**Issue by kawaii-Code** [kawaii-Code/neko-mission#6]
Сделать так, чтобы можно было задать начальную и конечную точку для врага. Враг (пока что один, спавнить как в гифке не нужно) будет начинать в этой начальной точке и идти до конечной. Враг должен идти не по прямой, а по списку точек, который нужно как-то получать, например по позициям определённых тайлов.

1. Нужна начальная карта с маршрутом, по которому враг будет идти, если её пока что нету - можно сделать что-нибудь просто для демонстрации идеи, на кубах (как в прототипе)
2. Сделать самого врага - просто куб
3. Найти маршрут от самого врага точки до его назначения
4. Сделать так, чтобы враг шёл по этому маршруту

К заданию два требования - чтобы работало, и чтобы не было очень неэффективно: не нужно для каждого врага каждый кадр пересчитывать маршрут.

![enemy_route](https://github.com/kawaii-Code/neko-mission/assets/108984073/9116f8a5-1365-4903-a584-84142cb91607)

**Comment by MakimaGorky** [comment]
![Enemy_AI_Demo](https://github.com/kawaii-Code/neko-mission/assets/114951816/b85060f3-1f88-4138-85f2-46b3e84e1594)

**Comment by kawaii-Code** [comment]
Очень смешные ДГТУшники

**Comment by MakimaGorky** [comment]
враги не должны быть умными😎

**Comment by kawaii-Code** [comment]
Рано радуешься
